#' DNA methylation data (beta-values) for the CODAM cohort.
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' The generation of genome-wide DNA methylation data is described by Bonder et al. (doi:10.1038/ng.3721).
#' Briefly, 500 ng of genomic DNA was bisulfite modified using the EZ DNA Methylation kit (Zymo Research, Irvine, CA, USA)
#' and hybridized on Illumina 450K arrays according to the manufacturer's protocols.
#' The original idat files were generated by the Illumina iScan BeadChip scanner.
#' Subsequently, sample quality control was performed using MethylAid.
#' Probes with a high detection P value (> 0.01), probes with a low bead count (< 3 beads), and probes with a low success rate
#' (missing in > 95% of the samples) were set to missing. Samples containing an excess of missing probes (> 5%) were excluded
#' from the analysis. Subsequently, per cohort, imputation was performed to impute the missing values. Functional normalization,
#' as implemented in the minfi package , was used per cohort.
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name methData_Betas_CODAM_Freeze2_unrelated
#' @usage data(methData_Betas_CODAM_Freeze2_unrelated
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(methData_Betas_CODAM_Freeze2_unrelated)
#' betas
methData_Betas_CODAM_Freeze2_unrelated <- NULL

#' DNA methylation data (M-values) for the CODAM cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' The generation of genome-wide DNA methylation data is described by Bonder et al. (doi:10.1038/ng.3721).
#' Briefly, 500 ng of genomic DNA was bisulfite modified using the EZ DNA Methylation kit (Zymo Research, Irvine, CA, USA)
#' and hybridized on Illumina 450K arrays according to the manufacturer's protocols.
#' The original idat files were generated by the Illumina iScan BeadChip scanner.
#' Subsequently, sample quality control was performed using MethylAid.
#' Probes with a high detection P value (> 0.01), probes with a low bead count (< 3 beads), and probes with a low success rate
#' (missing in > 95% of the samples) were set to missing. Samples containing an excess of missing probes (> 5%) were excluded
#' from the analysis. Subsequently, per cohort, imputation was performed to impute the missing values. Functional normalization,
#' as implemented in the minfi package , was used per cohort.
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name methData_Mvalues_CODAM_Freeze2_unrelated
#' @usage data(methData_Mvalues_CODAM_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(methData_Mvalues_CODAM_Freeze2_unrelated)
#' mvalues
methData_Mvalues_CODAM_Freeze2_unrelated <- NULL

#' DNA methylation data (beta-values) for the LL cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' The generation of genome-wide DNA methylation data is described by Bonder et al. (doi:10.1038/ng.3721).
#' Briefly, 500 ng of genomic DNA was bisulfite modified using the EZ DNA Methylation kit (Zymo Research, Irvine, CA, USA)
#' and hybridized on Illumina 450K arrays according to the manufacturer's protocols.
#' The original idat files were generated by the Illumina iScan BeadChip scanner.
#' Subsequently, sample quality control was performed using MethylAid.
#' Probes with a high detection P value (> 0.01), probes with a low bead count (< 3 beads), and probes with a low success rate
#' (missing in > 95% of the samples) were set to missing. Samples containing an excess of missing probes (> 5%) were excluded
#' from the analysis. Subsequently, per cohort, imputation was performed to impute the missing values. Functional normalization,
#' as implemented in the minfi package , was used per cohort.
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name methData_Betas_LL_Freeze2_unrelated
#' @usage data(methData_Betas_LL_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(methData_Betas_LL_Freeze2_unrelated)
#' betas
methData_Betas_LL_Freeze2_unrelated <- NULL

#' DNA methylation data (M-values) for the LL cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' The generation of genome-wide DNA methylation data is described by Bonder et al. (doi:10.1038/ng.3721).
#' Briefly, 500 ng of genomic DNA was bisulfite modified using the EZ DNA Methylation kit (Zymo Research, Irvine, CA, USA)
#' and hybridized on Illumina 450K arrays according to the manufacturer's protocols.
#' The original idat files were generated by the Illumina iScan BeadChip scanner.
#' Subsequently, sample quality control was performed using MethylAid.
#' Probes with a high detection P value (> 0.01), probes with a low bead count (< 3 beads), and probes with a low success rate
#' (missing in > 95% of the samples) were set to missing. Samples containing an excess of missing probes (> 5%) were excluded
#' from the analysis. Subsequently, per cohort, imputation was performed to impute the missing values. Functional normalization,
#' as implemented in the minfi package , was used per cohort.
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name methData_Mvalues_LL_Freeze2_unrelated
#' @usage data(methData_Mvalues_LL_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(methData_Mvalues_LL_Freeze2_unrelated)
#' mvalues
methData_Mvalues_LL_Freeze2_unrelated <- NULL

#' DNA methylation data (beta-values) for the LLS cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' The generation of genome-wide DNA methylation data is described by Bonder et al. (doi:10.1038/ng.3721).
#' Briefly, 500 ng of genomic DNA was bisulfite modified using the EZ DNA Methylation kit (Zymo Research, Irvine, CA, USA)
#' and hybridized on Illumina 450K arrays according to the manufacturer's protocols.
#' The original idat files were generated by the Illumina iScan BeadChip scanner.
#' Subsequently, sample quality control was performed using MethylAid.
#' Probes with a high detection P value (> 0.01), probes with a low bead count (< 3 beads), and probes with a low success rate
#' (missing in > 95% of the samples) were set to missing. Samples containing an excess of missing probes (> 5%) were excluded
#' from the analysis. Subsequently, per cohort, imputation was performed to impute the missing values. Functional normalization,
#' as implemented in the minfi package , was used per cohort.
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name methData_Betas_LLS_Freeze2_unrelated
#' @usage data(methData_Betas_LLS_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(methData_Betas_LLS_Freeze2_unrelated)
#' betas
methData_Betas_LLS_Freeze2_unrelated <- NULL

#' DNA methylation data (M-values) for the LLS cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' The generation of genome-wide DNA methylation data is described by Bonder et al. (doi:10.1038/ng.3721).
#' Briefly, 500 ng of genomic DNA was bisulfite modified using the EZ DNA Methylation kit (Zymo Research, Irvine, CA, USA)
#' and hybridized on Illumina 450K arrays according to the manufacturer's protocols.
#' The original idat files were generated by the Illumina iScan BeadChip scanner.
#' Subsequently, sample quality control was performed using MethylAid.
#' Probes with a high detection P value (> 0.01), probes with a low bead count (< 3 beads), and probes with a low success rate
#' (missing in > 95% of the samples) were set to missing. Samples containing an excess of missing probes (> 5%) were excluded
#' from the analysis. Subsequently, per cohort, imputation was performed to impute the missing values. Functional normalization,
#' as implemented in the minfi package , was used per cohort.
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name methData_Mvalues_LLS_Freeze2_unrelated
#' @usage data(methData_Mvalues_LLS_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(methData_Mvalues_LLS_Freeze2_unrelated)
#' mvalues
methData_Mvalues_LLS_Freeze2_unrelated <- NULL

#' DNA methylation data (beta-values) for the NTR cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' The generation of genome-wide DNA methylation data is described by Bonder et al. (doi:10.1038/ng.3721).
#' Briefly, 500 ng of genomic DNA was bisulfite modified using the EZ DNA Methylation kit (Zymo Research, Irvine, CA, USA)
#' and hybridized on Illumina 450K arrays according to the manufacturer's protocols.
#' The original idat files were generated by the Illumina iScan BeadChip scanner.
#' Subsequently, sample quality control was performed using MethylAid.
#' Probes with a high detection P value (> 0.01), probes with a low bead count (< 3 beads), and probes with a low success rate
#' (missing in > 95% of the samples) were set to missing. Samples containing an excess of missing probes (> 5%) were excluded
#' from the analysis. Subsequently, per cohort, imputation was performed to impute the missing values. Functional normalization,
#' as implemented in the minfi package , was used per cohort.
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name methData_Betas_NTR_Freeze2_unrelated
#' @usage data(methData_Betas_NTR_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(methData_Betas_NTR_Freeze2_unrelated)
#' betas
methData_Betas_NTR_Freeze2_unrelated <- NULL

#' DNA methylation data (M-values) for the NTR cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' The generation of genome-wide DNA methylation data is described by Bonder et al. (doi:10.1038/ng.3721).
#' Briefly, 500 ng of genomic DNA was bisulfite modified using the EZ DNA Methylation kit (Zymo Research, Irvine, CA, USA)
#' and hybridized on Illumina 450K arrays according to the manufacturer's protocols.
#' The original idat files were generated by the Illumina iScan BeadChip scanner.
#' Subsequently, sample quality control was performed using MethylAid.
#' Probes with a high detection P value (> 0.01), probes with a low bead count (< 3 beads), and probes with a low success rate
#' (missing in > 95% of the samples) were set to missing. Samples containing an excess of missing probes (> 5%) were excluded
#' from the analysis. Subsequently, per cohort, imputation was performed to impute the missing values. Functional normalization,
#' as implemented in the minfi package , was used per cohort.
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name methData_Mvalues_NTR_Freeze2_unrelated
#' @usage data(methData_Mvalues_NTR_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(methData_Mvalues_NTR_Freeze2_unrelated)
#' mvalues
methData_Mvalues_NTR_Freeze2_unrelated <- NULL

#' DNA methylation data (beta-values) for the RS cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' The generation of genome-wide DNA methylation data is described by Bonder et al. (doi:10.1038/ng.3721).
#' Briefly, 500 ng of genomic DNA was bisulfite modified using the EZ DNA Methylation kit (Zymo Research, Irvine, CA, USA)
#' and hybridized on Illumina 450K arrays according to the manufacturer's protocols.
#' The original idat files were generated by the Illumina iScan BeadChip scanner.
#' Subsequently, sample quality control was performed using MethylAid.
#' Probes with a high detection P value (> 0.01), probes with a low bead count (< 3 beads), and probes with a low success rate
#' (missing in > 95% of the samples) were set to missing. Samples containing an excess of missing probes (> 5%) were excluded
#' from the analysis. Subsequently, per cohort, imputation was performed to impute the missing values. Functional normalization,
#' as implemented in the minfi package , was used per cohort.
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name methData_Betas_RS_Freeze2_unrelated
#' @usage data(methData_Betas_RS_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(methData_Betas_RS_Freeze2_unrelated)
#' betas
methData_Betas_RS_Freeze2_unrelated <- NULL

#' DNA methylation data (M-values) for the RS cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' The generation of genome-wide DNA methylation data is described by Bonder et al. (doi:10.1038/ng.3721).
#' Briefly, 500 ng of genomic DNA was bisulfite modified using the EZ DNA Methylation kit (Zymo Research, Irvine, CA, USA)
#' and hybridized on Illumina 450K arrays according to the manufacturer's protocols.
#' The original idat files were generated by the Illumina iScan BeadChip scanner.
#' Subsequently, sample quality control was performed using MethylAid.
#' Probes with a high detection P value (> 0.01), probes with a low bead count (< 3 beads), and probes with a low success rate
#' (missing in > 95% of the samples) were set to missing. Samples containing an excess of missing probes (> 5%) were excluded
#' from the analysis. Subsequently, per cohort, imputation was performed to impute the missing values. Functional normalization,
#' as implemented in the minfi package , was used per cohort.
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name methData_Mvalues_RS_Freeze2_unrelated
#' @usage data(methData_Mvalues_RS_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(methData_Mvalues_RS_Freeze2_unrelated)
#' mvalues
methData_Mvalues_RS_Freeze2_unrelated <- NULL

#' DNA methylation data (beta-values) for the PAN cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' The generation of genome-wide DNA methylation data is described by Bonder et al. (doi:10.1038/ng.3721).
#' Briefly, 500 ng of genomic DNA was bisulfite modified using the EZ DNA Methylation kit (Zymo Research, Irvine, CA, USA)
#' and hybridized on Illumina 450K arrays according to the manufacturer's protocols.
#' The original idat files were generated by the Illumina iScan BeadChip scanner.
#' Subsequently, sample quality control was performed using MethylAid.
#' Probes with a high detection P value (> 0.01), probes with a low bead count (< 3 beads), and probes with a low success rate
#' (missing in > 95% of the samples) were set to missing. Samples containing an excess of missing probes (> 5%) were excluded
#' from the analysis. Subsequently, per cohort, imputation was performed to impute the missing values. Functional normalization,
#' as implemented in the minfi package , was used per cohort.
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name methData_Betas_PAN_Freeze2_unrelated
#' @usage data(methData_Betas_PAN_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(methData_Betas_PAN_Freeze2_unrelated)
#' betas
methData_Betas_PAN_Freeze2_unrelated <- NULL

#' DNA methylation data (M-values) for the PAN cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' The generation of genome-wide DNA methylation data is described by Bonder et al. (doi:10.1038/ng.3721).
#' Briefly, 500 ng of genomic DNA was bisulfite modified using the EZ DNA Methylation kit (Zymo Research, Irvine, CA, USA)
#' and hybridized on Illumina 450K arrays according to the manufacturer's protocols.
#' The original idat files were generated by the Illumina iScan BeadChip scanner.
#' Subsequently, sample quality control was performed using MethylAid.
#' Probes with a high detection P value (> 0.01), probes with a low bead count (< 3 beads), and probes with a low success rate
#' (missing in > 95% of the samples) were set to missing. Samples containing an excess of missing probes (> 5%) were excluded
#' from the analysis. Subsequently, per cohort, imputation was performed to impute the missing values. Functional normalization,
#' as implemented in the minfi package , was used per cohort.
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name methData_Mvalues_PAN_Freeze2_unrelated
#' @usage data(methData_Mvalues_PAN_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(methData_Mvalues_PAN_Freeze2_unrelated)
#' mvalues
methData_Mvalues_PAN_Freeze2_unrelated <- NULL

#' DNA methylation data (beta-values) for BIOS
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' The generation of genome-wide DNA methylation data is described by Bonder et al. (doi:10.1038/ng.3721).
#' Briefly, 500 ng of genomic DNA was bisulfite modified using the EZ DNA Methylation kit (Zymo Research, Irvine, CA, USA)
#' and hybridized on Illumina 450K arrays according to the manufacturer's protocols.
#' The original idat files were generated by the Illumina iScan BeadChip scanner.
#' Subsequently, sample quality control was performed using MethylAid.
#' Probes with a high detection P value (> 0.01), probes with a low bead count (< 3 beads), and probes with a low success rate
#' (missing in > 95% of the samples) were set to missing. Samples containing an excess of missing probes (> 5%) were excluded
#' from the analysis. Subsequently, per cohort, imputation was performed to impute the missing values. Functional normalization,
#' as implemented in the minfi package , was used per cohort.
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name methData_Betas_BIOS_Freeze2_unrelated
#' @usage data(methData_Betas_BIOS_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(methData_Betas_BIOS_Freeze2_unrelated)
#' betas
methData_Betas_BIOS_Freeze2_unrelated <- NULL

#' DNA methylation data (M-values) for BIOS
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' The generation of genome-wide DNA methylation data is described by Bonder et al. (doi:10.1038/ng.3721).
#' Briefly, 500 ng of genomic DNA was bisulfite modified using the EZ DNA Methylation kit (Zymo Research, Irvine, CA, USA)
#' and hybridized on Illumina 450K arrays according to the manufacturer's protocols.
#' The original idat files were generated by the Illumina iScan BeadChip scanner.
#' Subsequently, sample quality control was performed using MethylAid.
#' Probes with a high detection P value (> 0.01), probes with a low bead count (< 3 beads), and probes with a low success rate
#' (missing in > 95% of the samples) were set to missing. Samples containing an excess of missing probes (> 5%) were excluded
#' from the analysis. Subsequently, per cohort, imputation was performed to impute the missing values. Functional normalization,
#' as implemented in the minfi package , was used per cohort.
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name methData_Mvalues_BIOS_Freeze2_unrelated
#' @usage data(methData_Mvalues_BIOS_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(methData_Mvalues_BIOS_Freeze2_unrelated)
#' mvalues
methData_Mvalues_BIOS_Freeze2_unrelated <- NULL

#' RNAseq data for the CODAM cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' A detailed description of the RNA-seq data processing can be found in Zhernakova et al. (doi:10.1038/ng.3737).
#' Briefly, total RNA from whole blood, depleted of globin transcripts, was sequenced (2x50-bp) using the Illumina
#' HiSeq 2000 platform, and read alignment was performed using STAR (v2.3.0).
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name rnaSeqData_ReadCounts_CODAM_Freeze2_unrelated
#' @usage data(rnaSeqData_ReadCounts_CODAM_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(rnaSeqData_ReadCounts_CODAM_Freeze2_unrelated)
#' counts
rnaSeqData_ReadCounts_CODAM_Freeze2_unrelated <- NULL

#' RNAseq data for the LL cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' A detailed description of the RNA-seq data processing can be found in Zhernakova et al. (doi:10.1038/ng.3737).
#' Briefly, total RNA from whole blood, depleted of globin transcripts, was sequenced (2x50-bp) using the Illumina
#' HiSeq 2000 platform, and read alignment was performed using STAR (v2.3.0).
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name rnaSeqData_ReadCounts_LL_Freeze2_unrelated
#' @usage data(rnaSeqData_ReadCounts_LL_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(rnaSeqData_ReadCounts_LL_Freeze2_unrelated)
#' counts
rnaSeqData_ReadCounts_LL_Freeze2_unrelated <- NULL

#' RNAseq data for the LLS cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' A detailed description of the RNA-seq data processing can be found in Zhernakova et al. (doi:10.1038/ng.3737).
#' Briefly, total RNA from whole blood, depleted of globin transcripts, was sequenced (2x50-bp) using the Illumina
#' HiSeq 2000 platform, and read alignment was performed using STAR (v2.3.0).
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name rnaSeqData_ReadCounts_LLS_Freeze2_unrelated
#' @usage data(rnaSeqData_ReadCounts_LLS_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(rnaSeqData_ReadCounts_LLS_Freeze2_unrelated)
#' counts
rnaSeqData_ReadCounts_LLS_Freeze2_unrelated <- NULL

#' RNAseq data for the NTR cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' A detailed description of the RNA-seq data processing can be found in Zhernakova et al. (doi:10.1038/ng.3737).
#' Briefly, total RNA from whole blood, depleted of globin transcripts, was sequenced (2x50-bp) using the Illumina
#' HiSeq 2000 platform, and read alignment was performed using STAR (v2.3.0).
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name rnaSeqData_ReadCounts_NTR_Freeze2_unrelated
#' @usage data(rnaSeqData_ReadCounts_NTR_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(rnaSeqData_ReadCounts_NTR_Freeze2_unrelated)
#' counts
rnaSeqData_ReadCounts_NTR_Freeze2_unrelated <- NULL

#' RNAseq data for the PAN cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' A detailed description of the RNA-seq data processing can be found in Zhernakova et al. (doi:10.1038/ng.3737).
#' Briefly, total RNA from whole blood, depleted of globin transcripts, was sequenced (2x50-bp) using the Illumina
#' HiSeq 2000 platform, and read alignment was performed using STAR (v2.3.0).
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name rnaSeqData_ReadCounts_PAN_Freeze2_unrelated
#' @usage data(rnaSeqData_ReadCounts_PAN_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(rnaSeqData_ReadCounts_PAN_Freeze2_unrelated)
#' counts
rnaSeqData_ReadCounts_PAN_Freeze2_unrelated <- NULL

#' RNAseq data for the RS cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' A detailed description of the RNA-seq data processing can be found in Zhernakova et al. (doi:10.1038/ng.3737).
#' Briefly, total RNA from whole blood, depleted of globin transcripts, was sequenced (2x50-bp) using the Illumina
#' HiSeq 2000 platform, and read alignment was performed using STAR (v2.3.0).
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name rnaSeqData_ReadCounts_RS_Freeze2_unrelated
#' @usage data(rnaSeqData_ReadCounts_RS_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(rnaSeqData_ReadCounts_RS_Freeze2_unrelated)
#' counts
rnaSeqData_ReadCounts_RS_Freeze2_unrelated <- NULL

#' RNAseq data for BIOS
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' A detailed description of the RNA-seq data processing can be found in Zhernakova et al. (doi:10.1038/ng.3737).
#' Briefly, total RNA from whole blood, depleted of globin transcripts, was sequenced (2x50-bp) using the Illumina
#' HiSeq 2000 platform, and read alignment was performed using STAR (v2.3.0).
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name rnaSeqData_ReadCounts_BIOS_Freeze2_unrelated
#' @usage data(rnaSeqData_ReadCounts_BIOS_Freeze2_unrelated)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(rnaSeqData_ReadCounts_BIOS_Freeze2_unrelated)
#' counts
rnaSeqData_ReadCounts_BIOS_Freeze2_unrelated <- NULL

#' RNAseq data for BIOS GoNL subset
#'
#' A detailed description of the RNA-seq data processing can be found in Zhernakova et al. (doi:10.1038/ng.3737).
#' Briefly, total RNA from whole blood, depleted of globin transcripts, was sequenced (2x50-bp) using the Illumina
#' HiSeq 2000 platform, and read alignment was performed using STAR (v2.3.0).
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name rnaSeqData_ReadCounts_BIOS_Freeze2_GoNL
#' @usage data(rnaSeqData_ReadCounts_BIOS_Freeze2_GoNL)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(rnaSeqData_ReadCounts_BIOS_Freeze2_GoNL)
#' counts
rnaSeqData_ReadCounts_BIOS_Freeze2_GoNL <- NULL

#' RNAseq data for BIOS GoNL subset
#'
#' A detailed description of the RNA-seq data processing can be found in Zhernakova et al. (doi:10.1038/ng.3737).
#' Briefly, total RNA from whole blood, depleted of globin transcripts, was sequenced (2x50-bp) using the Illumina
#' HiSeq 2000 platform, and read alignment was performed using STAR (v2.5.3a).
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name rnaSeqData_ReadCounts_BIOS_Freeze2_GoNL_GRCh38
#' @usage data(rnaSeqData_ReadCounts_BIOS_Freeze2_GoNL_GRCh38)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(rnaSeqData_ReadCounts_BIOS_Freeze2_GoNL_GRCh38)
#' counts
rnaSeqData_ReadCounts_BIOS_Freeze2_GoNL_GRCh38 <- NULL

#' RNAseq data for BIOS
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' A detailed description of the RNA-seq data processing can be found in Zhernakova et al. (doi:10.1038/ng.3737).
#' Briefly, total RNA from whole blood, depleted of globin transcripts, was sequenced (2x50-bp) using the Illumina
#' HiSeq 2000 platform, and read alignment was performed using STAR (v2.5.3a).
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name rnaSeqData_ReadCounts_BIOS_Freeze2_unrelated_GRCh38
#' @usage data(rnaSeqData_ReadCounts_BIOS_Freeze2_unrelated_GRCh38)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(rnaSeqData_ReadCounts_BIOS_Freeze2_unrelated_GRCh38)
#' counts
rnaSeqData_ReadCounts_BIOS_Freeze2_unrelated_GRCh38 <- NULL

#' RNAseq data for the CODAM cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' A detailed description of the RNA-seq data processing can be found in Zhernakova et al. (doi:10.1038/ng.3737).
#' Briefly, total RNA from whole blood, depleted of globin transcripts, was sequenced (2x50-bp) using the Illumina
#' HiSeq 2000 platform, and read alignment was performed using STAR (v2.5.3a).
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name rnaSeqData_ReadCounts_CODAM_Freeze2_unrelated_GRCh38
#' @usage data(rnaSeqData_ReadCounts_CODAM_Freeze2_unrelated_GRCh38)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(rnaSeqData_ReadCounts_CODAM_Freeze2_unrelated_GRCh38)
#' counts
rnaSeqData_ReadCounts_CODAM_Freeze2_unrelated_GRCh38 <- NULL

#' RNAseq data for the LL cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' A detailed description of the RNA-seq data processing can be found in Zhernakova et al. (doi:10.1038/ng.3737).
#' Briefly, total RNA from whole blood, depleted of globin transcripts, was sequenced (2x50-bp) using the Illumina
#' HiSeq 2000 platform, and read alignment was performed using STAR (v2.5.3a).
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name rnaSeqData_ReadCounts_LL_Freeze2_unrelated_GRCh38
#' @usage data(rnaSeqData_ReadCounts_LL_Freeze2_unrelated_GRCh38)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(rnaSeqData_ReadCounts_LL_Freeze2_unrelated_GRCh38)
#' counts
rnaSeqData_ReadCounts_LL_Freeze2_unrelated_GRCh38 <- NULL

#' RNAseq data for the LLS cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' A detailed description of the RNA-seq data processing can be found in Zhernakova et al. (doi:10.1038/ng.3737).
#' Briefly, total RNA from whole blood, depleted of globin transcripts, was sequenced (2x50-bp) using the Illumina
#' HiSeq 2000 platform, and read alignment was performed using STAR (v2.5.3a).
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name rnaSeqData_ReadCounts_LLS_Freeze2_unrelated_GRCh38
#' @usage data(rnaSeqData_ReadCounts_LLS_Freeze2_unrelated_GRCh38)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(rnaSeqData_ReadCounts_LLS_Freeze2_unrelated_GRCh38)
#' counts
rnaSeqData_ReadCounts_LLS_Freeze2_unrelated_GRCh38 <- NULL

#' RNAseq data for the NTR cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' A detailed description of the RNA-seq data processing can be found in Zhernakova et al. (doi:10.1038/ng.3737).
#' Briefly, total RNA from whole blood, depleted of globin transcripts, was sequenced (2x50-bp) using the Illumina
#' HiSeq 2000 platform, and read alignment was performed using STAR (v2.5.3a).
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name rnaSeqData_ReadCounts_NTR_Freeze2_unrelated_GRCh38
#' @usage data(rnaSeqData_ReadCounts_NTR_Freeze2_unrelated_GRCh38)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(rnaSeqData_ReadCounts_NTR_Freeze2_unrelated_GRCh38)
#' counts
rnaSeqData_ReadCounts_NTR_Freeze2_unrelated_GRCh38 <- NULL

#' RNAseq data for the PAN cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' A detailed description of the RNA-seq data processing can be found in Zhernakova et al. (doi:10.1038/ng.3737).
#' Briefly, total RNA from whole blood, depleted of globin transcripts, was sequenced (2x50-bp) using the Illumina
#' HiSeq 2000 platform, and read alignment was performed using STAR (v2.5.3a).
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name rnaSeqData_ReadCounts_PAN_Freeze2_unrelated_GRCh38
#' @usage data(rnaSeqData_ReadCounts_PAN_Freeze2_unrelated_GRCh38)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(rnaSeqData_ReadCounts_PAN_Freeze2_unrelated_GRCh38)
#' counts
rnaSeqData_ReadCounts_PAN_Freeze2_unrelated_GRCh38 <- NULL

#' RNAseq data for the RS cohort
#'
#' This dataset only includes the samples from the Freeze2 unrelated set, which
#' contains a maximum set of unrelated individuals.
#'
#' A detailed description of the RNA-seq data processing can be found in Zhernakova et al. (doi:10.1038/ng.3737).
#' Briefly, total RNA from whole blood, depleted of globin transcripts, was sequenced (2x50-bp) using the Illumina
#' HiSeq 2000 platform, and read alignment was performed using STAR (v2.5.3a).
#'
#' DNA methylation data and RNA-seq data were generated within the Biobank-based Integrative Omics Studies Consortium (http://wiki.bbmri.nl/wiki/BIOS_start-).
#' The data comprise six biobanks: Cohort on Diabetes and Atherosclerosis Maastricht (CODAM, n~180)
#' (doi: 10.1111/j.1365-2362.2010.02418.x), LifeLines (LL, n~700) (doi: 10.1136/bmjopen-2014-006772),
#' the Leiden Longevity Study (LLS, n~600) (doi: 10.1111/j.1532-5415.2009.02381.x),
#' the Rotterdam Study (RS, n~600) (doi: 10.1007/s10654-011-9610-5),
#' the Netherlands Twin Registry (NTR, n~1800) (doi:  10.1017/thg.2012.140) and
#' the Prospective ALS Study Netherlands (PAN, n~180) (doi: 10.1136/jnnp.2011.244939).
#' Sample identity of DNA methylation and gene expression data was confirmed using genotype data.
#'
#' Data were generated by the Human Genotyping facility (HugeF) of ErasmusMC, the Netherlands (www.glimDNA.org).
#'
#' @docType data
#' @name rnaSeqData_ReadCounts_RS_Freeze2_unrelated_GRCh38
#' @usage data(rnaSeqData_ReadCounts_RS_Freeze2_unrelated_GRCh38)
#'
#' @format An object of class \code{"SummarizedExperiment"}; see \code{\link[SummarizedExperiment]{SummarizedExperiment}}.
#'
#' @keywords datasets
#' @export
#' @examples
#' data(rnaSeqData_ReadCounts_RS_Freeze2_unrelated_GRCh38)
#' counts
rnaSeqData_ReadCounts_RS_Freeze2_unrelated_GRCh38 <- NULL

#' RP3 RP4 Metadatabase
#'
#' This dataset contains a series of data.frame objects with the metadata for the RP3 and RP4 sample and experiments. 
#' Including phenotype information. Nightingale measurements are also included.
#'
#' The dataset contains two types of tables. Tables with raw metadata and tables (or views) with pregenerated subsets/aggregates.
#' The tables with the raw metadata are dna_sample, gwas, imputation, methylation_450k_freeze, methylation_450k_run, nightingale_quantification, 
#' nightingale_run, person, relation, rna_freeze, rna_merged_run, rna_run, rna_sample and visit. The remaining objects are views.
#'
#' @docType data
#' @name rp3_rp4_meta
#' @usage data(rp3_rp4_meta)
#'
#' @keywords datasets
#' @export
#' @examples
#' data(rp3_rp4_meta)
#' visit
rp3_rp4_meta <- NULL
