---
title: "Contribute to this website"
output: 
  html_document:
    highlight: tango
    toc: true
    toc_float:
      collapsed: false
bibliography: BBMRIomics.bib
---

We welcome contributions to [this website](bios-vm.bbmrirp3-lumc.surf-hosted.nl/BBMRIomics/)
web-site, for example, with use-cases. The BBMRIomics website is built entirely
using \<R\>. Specifically, [R\ Markdown](http://rmarkdown.rstudio.com/) is used
to generate the complete website from a few R\ Markdown files. [This section of
the RStudio R\ Markdown website](http://rmarkdown.rstudio.com/rmarkdown_websites.html)
shows how easy it is to generate a website using R\ Markdown.


## Adding a use-case ##

Modify `_site.yml` (Note dated 2017-03-17 14:45 : currently this file is accessible
on the BIOS VM in "/virdir/Scratch/RP3_analysis/BBMRIomics/site_package") by adding
a new use-case under the use-case items, *e.g.*: 

<!-- Note dd 2017-03-17 14:56 (HD): "Bash" (below) 'was about as good as R Markdown got'... -->
```bash
- text: "eqtl analysis"
  href: eqtl.html
```
  
*Beware: spacing **does** matter!*

Now, from within the `site_package` directory generate a new template by entering
from the Ubuntu command prompt:

```bash
$ make newpage file=eqtl
```

This will generate `eqtl.Rmd` for you with the same settings as the other \*.Rmd
files in this folder. Provide your example with documentation and use `cache=TRUE`
as an argument for the \<R\> code chunk (perhaps check one of the other \*.Rmd
documents).

<!-- For more information on [R\ Markdown](http://rmarkdown.rstudio.com/). -->

Check if all code chunks run without errors -- optionally add a library to
`_setup.Rmd`. Then enter at the Ubuntu command prompt the following command:

```bash
$ make render
```

..., and, if successfully run:

```bash
$ sudo make publish
```

<!-- END OF FILE. -->
